### PR TITLE
Fix lints and issues

### LINKED ISSUE #2: GPR's can't have '-' in the name, so the command line argument should be rewritten
Using your example in the `README.md` `$ gnatgen new project my-project` the GPR will be created with `project my-project` for which `my-project` is an invalid name literal. As such `-` should be rewritten into another character, probably `_`.

### PR DESCRIPTION
**Pull request by psyomn**
Closes #2, #3 

Thanks for bringing up the issues @Entomy! 

I forgot I had written this a few years ago, and revisiting some of the source sent me back memory lane. 

I'd like to mention that I kind of wrote a good portion of this expecting no one to ever use this, so sorry if this caused you any grief; cheers! 

(Also #1 is relevant, but I'm just doing it for the case you mentioned for now)

Will go over this tomorrow and make sure that everything seems in line when I'm a little more awake, and probably merge!

### CODE REVIEW

**Comment by Entomy** [comment]
Oh actually, I have a YouTube channel and was doing a code review of this code. I had planned on fixing/improving some things for you since I knew there was at least a few people who would use this.

**Comment by Entomy** [comment]
(you might want to actually merge this, btw)

**Comment by psyomn** [comment]
I can close this PR if you want to go ahead and implement said thingies, didn't mean to ruin anyone's fun :).

**Comment by Entomy** [comment]
Well since you've already implemented a few things, I've already branched off this. As far as I can tell this is the only code generator for Ada, aside from basic snippets that purely exist within specific editors. There's definately a need/desire for this.

**Comment by psyomn** [comment]
Alright! The code needs a lot of love and care, and cleanups are very, very possible. Let me know if you have any questions, and I'll try to answer as best as I can! I'll go ahead and merge this.

**Pull request merged**
